name: e_commerce_app
description: "E-Commerce App"
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  card_swiper: 3.0.1
  intl:
  go_router: ^14.1.4
  flutter_animate: ^4.5.0
  flutter_snake_navigationbar: ^0.6.1
  font_awesome_flutter: ^10.7.0
  loading_animation_widget: ^1.2.1
  path: ^1.9.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  uuid: ^4.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

